name: CI
on: [push]
jobs:
  lint:
    name: ⬣ ESLint
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version: 18

      - name: 📥 Install deps
        run: yarn

      - name: 🔬 Lint
        run: yarn lint

  typecheck:
    name: ʦ TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version: 18

      - name: 📥 Install deps
        run: yarn

      - name: 🔎 Type check
        run: yarn typecheck
  test:
    name: 🧪 Jest
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version: 18

      - name: 📥 Install deps
        run: yarn

      - name: 🔬 Test
        run: yarn test
